import Locality from '../models/Locality.js'

// Comprehensive locality data for multiple Indian cities
const LOCALITIES_BY_CITY = {
	Delhi: [
		{
			name: 'Sector 57',
			city: 'Gurugram',
			state: 'Haryana',
			avgPricePerSqFt: 14500,
			growthPercentage: 5.2,
			sixMonthGrowth: 5.2,
			yearGrowth: 7.8,
			coordinates: { lat: 28.4595, lng: 77.0592 },
			geo: { type: 'Point', coordinates: [77.0592, 28.4595] },
			ratings: { safety: 8.5, connectivity: 9.2, lifestyle: 8.4, overall: 8.7 },
			amenities: {
				schools: 5,
				hospitals: 7,
				metro: true,
				markets: 10,
				parks: 3,
				malls: 4,
				banks: 8,
			},
			nearbyMetros: [
				{ name: 'Huda City Centre', distance: 2.5 },
				{ name: 'Eesplanade', distance: 4.2 },
			],
			nearbySchools: [
				{ name: 'Delhi Public School', type: 'private', distance: 1.5 },
				{ name: 'Ryan International', type: 'private', distance: 2.1 },
			],
			nearbyHospitals: [
				{ name: 'Artemis', distance: 1.8 },
				{ name: 'Fortis', distance: 2.3 },
			],
			pros: [
				'Great Connectivity',
				'Modern Infrastructure',
				'Nearby Huda City Centre',
				'Upscale Shopping',
				'Well Planned Roads',
			],
			cons: [
				'Traffic Congestion',
				'Higher Living Cost',
				'Parking Issues',
				'Crowded During Peak Hours',
			],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 13800 },
				{ month: 'Feb 2024', averagePrice: 14000 },
				{ month: 'Mar 2024', averagePrice: 14200 },
				{ month: 'Apr 2024', averagePrice: 14500 },
			],
			neighboringLocalities: ['Sector 56', 'Sector 50', 'Sushant Lok 2'],
			description:
				'Sector 57 is a prime residential locality in Gurugram offering a mix of independent floors and apartments with excellent connectivity.',
			reviewCount: 245,
			averageRating: 4.2,
			searchCount: 8543,
			isPopular: true,
			developmentStatus: 'mature',
		},
		{
			name: 'Dwarka',
			city: 'Delhi',
			state: 'Delhi',
			avgPricePerSqFt: 8500,
			growthPercentage: 7.2,
			sixMonthGrowth: 7.2,
			yearGrowth: 10.5,
			coordinates: { lat: 28.5921, lng: 77.0434 },
			geo: { type: 'Point', coordinates: [77.0434, 28.5921] },
			ratings: { safety: 7.8, connectivity: 8.1, lifestyle: 7.5, overall: 7.8 },
			amenities: {
				schools: 8,
				hospitals: 5,
				metro: true,
				markets: 8,
				parks: 5,
				malls: 3,
				banks: 6,
			},
			nearbyMetros: [
				{ name: 'Dwarka Mor', distance: 1.2 },
				{ name: 'Dwarka', distance: 2.5 },
			],
			pros: [
				'Metro Accessible',
				'Family Friendly',
				'Good Schools',
				'Affordable',
				'Peaceful Area',
			],
			cons: ['Limited Shopping', 'Less Crowded Nightlife', 'Emerging Area'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 7800 },
				{ month: 'Feb 2024', averagePrice: 8000 },
				{ month: 'Mar 2024', averagePrice: 8300 },
				{ month: 'Apr 2024', averagePrice: 8500 },
			],
			neighboringLocalities: ['Uttam Nagar', 'Janakpuri', 'Rohini'],
			description: 'Dwarka is a well-planned residential area with excellent metro connectivity and family-friendly amenities.',
			reviewCount: 187,
			averageRating: 4.0,
			searchCount: 6234,
			isPopular: true,
			developmentStatus: 'developed',
		},
		{
			name: 'Saket',
			city: 'Delhi',
			state: 'Delhi',
			avgPricePerSqFt: 22000,
			growthPercentage: 3.8,
			sixMonthGrowth: 3.8,
			yearGrowth: 5.2,
			coordinates: { lat: 28.5244, lng: 77.1896 },
			geo: { type: 'Point', coordinates: [77.1896, 28.5244] },
			ratings: { safety: 8.7, connectivity: 8.3, lifestyle: 8.9, overall: 8.6 },
			amenities: {
				schools: 6,
				hospitals: 8,
				metro: true,
				markets: 12,
				parks: 4,
				malls: 5,
				banks: 10,
			},
			nearbyMetros: [{ name: 'Saket', distance: 0.8 }],
			pros: [
				'Upscale Area',
				'Shopping Mall Nearby',
				'Metro Station',
				'Green Spaces',
				'Luxury Shopping',
			],
			cons: ['Very Expensive', 'Crowded', 'Parking Difficult'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 21200 },
				{ month: 'Feb 2024', averagePrice: 21500 },
				{ month: 'Mar 2024', averagePrice: 21800 },
				{ month: 'Apr 2024', averagePrice: 22000 },
			],
			neighboringLocalities: ['Malviya Nagar', 'Vasant Kunj', 'Kalkaji'],
			description: 'Saket is one of Delhi\'s most upscale residential areas with premium amenities and excellent connectivity.',
			reviewCount: 356,
			averageRating: 4.5,
			searchCount: 11234,
			isPopular: true,
			developmentStatus: 'mature',
		},
	],
	Bangalore: [
		{
			name: 'Koramangala',
			city: 'Bangalore',
			state: 'Karnataka',
			avgPricePerSqFt: 12000,
			growthPercentage: 8.5,
			sixMonthGrowth: 8.5,
			yearGrowth: 12.3,
			coordinates: { lat: 12.9352, lng: 77.6245 },
			geo: { type: 'Point', coordinates: [77.6245, 12.9352] },
			ratings: { safety: 8.2, connectivity: 8.5, lifestyle: 8.8, overall: 8.5 },
			amenities: {
				schools: 7,
				hospitals: 6,
				metro: false,
				markets: 15,
				parks: 3,
				malls: 6,
				banks: 12,
			},
			nearbyMetros: [],
			pros: ['IT Hub', 'Great Nightlife', 'Shopping & Dining', 'Young Crowd', 'Startup Culture'],
			cons: ['Traffic Heavy', 'Expensive Dining', 'Parking Issues'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 10800 },
				{ month: 'Feb 2024', averagePrice: 11300 },
				{ month: 'Mar 2024', averagePrice: 11700 },
				{ month: 'Apr 2024', averagePrice: 12000 },
			],
			neighboringLocalities: ['Indiranagar', 'Bellandur', 'Jubilee Hills'],
			description: 'Koramangala is Bangalore\'s most vibrant locality, famous for its IT companies, restaurants, and nightlife.',
			reviewCount: 412,
			averageRating: 4.3,
			searchCount: 15623,
			isPopular: true,
			developmentStatus: 'mature',
		},
		{
			name: 'Whitefield',
			city: 'Bangalore',
			state: 'Karnataka',
			avgPricePerSqFt: 9000,
			growthPercentage: 9.2,
			sixMonthGrowth: 9.2,
			yearGrowth: 13.1,
			coordinates: { lat: 12.9698, lng: 77.7499 },
			geo: { type: 'Point', coordinates: [77.7499, 12.9698] },
			ratings: { safety: 7.9, connectivity: 8.2, lifestyle: 7.8, overall: 7.9 },
			amenities: {
				schools: 9,
				hospitals: 7,
				metro: false,
				markets: 8,
				parks: 4,
				malls: 4,
				banks: 7,
			},
			nearbyMetros: [],
			pros: [
				'IT Parks Nearby',
				'Affordable',
				'Growing Area',
				'Good Schools',
				'Safe & Clean',
			],
			cons: ['Less Entertainment', 'Still Developing', 'Limited Nightlife'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 8200 },
				{ month: 'Feb 2024', averagePrice: 8500 },
				{ month: 'Mar 2024', averagePrice: 8800 },
				{ month: 'Apr 2024', averagePrice: 9000 },
			],
			neighboringLocalities: ['Marathahalli', 'Sarjapur', 'HSR Layout'],
			description: 'Whitefield is a rapidly developing area with major IT parks, making it an ideal choice for tech professionals.',
			reviewCount: 234,
			averageRating: 4.1,
			searchCount: 9876,
			isPopular: true,
			developmentStatus: 'developing',
		},
	],
	Mumbai: [
		{
			name: 'Bandra',
			city: 'Mumbai',
			state: 'Maharashtra',
			avgPricePerSqFt: 28000,
			growthPercentage: 3.5,
			sixMonthGrowth: 3.5,
			yearGrowth: 4.8,
			coordinates: { lat: 19.076, lng: 72.8295 },
			geo: { type: 'Point', coordinates: [72.8295, 19.076] },
			ratings: { safety: 8.4, connectivity: 8.6, lifestyle: 9.1, overall: 8.7 },
			amenities: {
				schools: 6,
				hospitals: 8,
				metro: false,
				markets: 18,
				parks: 4,
				malls: 7,
				banks: 14,
			},
			nearbyMetros: [],
			pros: [
				'Premium Area',
				'Beachside Living',
				'Celebrity Hotspot',
				'Great Restaurants',
				'High-end Shopping',
			],
			cons: ['Extremely Expensive', 'Parking Nightmare', 'Crowded Beach'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 27000 },
				{ month: 'Feb 2024', averagePrice: 27400 },
				{ month: 'Mar 2024', averagePrice: 27700 },
				{ month: 'Apr 2024', averagePrice: 28000 },
			],
			neighboringLocalities: ['Kala Ghoda', 'Fort', 'Worli'],
			description: 'Bandra is Mumbai\'s most prestigious locality, known for its beaches, celebrity homes, and upscale lifestyle.',
			reviewCount: 534,
			averageRating: 4.4,
			searchCount: 18934,
			isPopular: true,
			developmentStatus: 'mature',
		},
		{
			name: 'Thane',
			city: 'Mumbai',
			state: 'Maharashtra',
			avgPricePerSqFt: 12500,
			growthPercentage: 7.9,
			sixMonthGrowth: 7.9,
			yearGrowth: 11.2,
			coordinates: { lat: 19.2183, lng: 72.9781 },
			geo: { type: 'Point', coordinates: [72.9781, 19.2183] },
			ratings: { safety: 7.6, connectivity: 8.0, lifestyle: 7.8, overall: 7.8 },
			amenities: {
				schools: 8,
				hospitals: 6,
				metro: false,
				markets: 10,
				parks: 5,
				malls: 3,
				banks: 8,
			},
			nearbyMetros: [],
			pros: ['Affordable', 'Family Friendly', 'Lake City', 'Better Traffic', 'Growing Infrastructure'],
			cons: ['Far from Mumbai', 'Limited Entertainment', 'Still Developing'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 11600 },
				{ month: 'Feb 2024', averagePrice: 12000 },
				{ month: 'Mar 2024', averagePrice: 12300 },
				{ month: 'Apr 2024', averagePrice: 12500 },
			],
			neighboringLocalities: ['Navi Mumbai', 'Panvel', 'Belapur'],
			description: 'Thane is a fast-growing city near Mumbai with more affordable real estate and family-oriented amenities.',
			reviewCount: 312,
			averageRating: 4.0,
			searchCount: 8765,
			isPopular: true,
			developmentStatus: 'developing',
		},
	],
	Hyderabad: [
		{
			name: 'Banjara Hills',
			city: 'Hyderabad',
			state: 'Telangana',
			avgPricePerSqFt: 8500,
			growthPercentage: 9.2,
			sixMonthGrowth: 9.2,
			yearGrowth: 13.5,
			coordinates: { lat: 17.3867, lng: 78.4483 },
			geo: { type: 'Point', coordinates: [78.4483, 17.3867] },
			ratings: { safety: 8.3, connectivity: 8.7, lifestyle: 8.6, overall: 8.5 },
			amenities: {
				schools: 7,
				hospitals: 8,
				metro: false,
				markets: 12,
				parks: 5,
				malls: 5,
				banks: 10,
			},
			nearbyMetros: [],
			pros: ['Upscale Locality', 'Good Schools', 'Green Area', 'Safe', 'Shopping & Dining'],
			cons: ['Expensive', 'Traffic Issues', 'Limited Public Transport'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 7600 },
				{ month: 'Feb 2024', averagePrice: 8000 },
				{ month: 'Mar 2024', averagePrice: 8300 },
				{ month: 'Apr 2024', averagePrice: 8500 },
			],
			neighboringLocalities: ['Jubilee Hills', 'Madhapur', 'Kondapur'],
			description: 'Banjara Hills is Hyderabad\'s premium residential area, known for its upscale living and excellent schools.',
			reviewCount: 287,
			averageRating: 4.2,
			searchCount: 10432,
			isPopular: true,
			developmentStatus: 'mature',
		},
		{
			name: 'Kondapur',
			city: 'Hyderabad',
			state: 'Telangana',
			avgPricePerSqFt: 6800,
			growthPercentage: 12.5,
			sixMonthGrowth: 12.5,
			yearGrowth: 17.8,
			coordinates: { lat: 17.4591, lng: 78.6614 },
			geo: { type: 'Point', coordinates: [78.6614, 17.4591] },
			ratings: { safety: 7.8, connectivity: 8.2, lifestyle: 7.9, overall: 8.0 },
			amenities: {
				schools: 6,
				hospitals: 5,
				metro: false,
				markets: 8,
				parks: 3,
				malls: 3,
				banks: 6,
			},
			nearbyMetros: [],
			pros: [
				'IT Hub',
				'Highly Affordable',
				'Emerging Area',
				'Good Growth',
				'Modern Infrastructure',
			],
			cons: ['Still Developing', 'Less Shopping', 'Limited Nightlife'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 5800 },
				{ month: 'Feb 2024', averagePrice: 6200 },
				{ month: 'Mar 2024', averagePrice: 6500 },
				{ month: 'Apr 2024', averagePrice: 6800 },
			],
			neighboringLocalities: ['HITEC City', 'Gachibowli', 'Madhapur'],
			description:
				'Kondapur is a rapidly developing IT hub with affordable property prices and strong growth potential.',
			reviewCount: 156,
			averageRating: 3.9,
			searchCount: 7234,
			isPopular: true,
			developmentStatus: 'developing',
		},
	],
	Pune: [
		{
			name: 'Hinjewadi',
			city: 'Pune',
			state: 'Maharashtra',
			avgPricePerSqFt: 6200,
			growthPercentage: 11.5,
			sixMonthGrowth: 11.5,
			yearGrowth: 16.2,
			coordinates: { lat: 18.5921, lng: 73.7197 },
			geo: { type: 'Point', coordinates: [73.7197, 18.5921] },
			ratings: { safety: 8.1, connectivity: 8.3, lifestyle: 8.0, overall: 8.1 },
			amenities: {
				schools: 8,
				hospitals: 6,
				metro: false,
				markets: 7,
				parks: 4,
				malls: 3,
				banks: 7,
			},
			nearbyMetros: [],
			pros: [
				'IT Park',
				'Affordable',
				'Tech Friendly',
				'Young Population',
				'Growing Area',
			],
			cons: ['Limited Entertainment', 'Still Under Development', 'Far from City Center'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 5200 },
				{ month: 'Feb 2024', averagePrice: 5700 },
				{ month: 'Mar 2024', averagePrice: 6000 },
				{ month: 'Apr 2024', averagePrice: 6200 },
			],
			neighboringLocalities: ['Baner', 'Wakad', 'Sus'],
			description: 'Hinjewadi is Pune\'s IT hub with excellent connectivity to tech parks and a growing residential base.',
			reviewCount: 198,
			averageRating: 4.0,
			searchCount: 8901,
			isPopular: true,
			developmentStatus: 'developing',
		},
		{
			name: 'Koregaon Park',
			city: 'Pune',
			state: 'Maharashtra',
			avgPricePerSqFt: 9500,
			growthPercentage: 7.2,
			sixMonthGrowth: 7.2,
			yearGrowth: 10.1,
			coordinates: { lat: 18.5295, lng: 73.9067 },
			geo: { type: 'Point', coordinates: [73.9067, 18.5295] },
			ratings: { safety: 8.4, connectivity: 8.5, lifestyle: 8.7, overall: 8.5 },
			amenities: {
				schools: 6,
				hospitals: 7,
				metro: false,
				markets: 10,
				parks: 3,
				malls: 4,
				banks: 9,
			},
			nearbyMetros: [],
			pros: ['Good Restaurants', 'Nightlife', 'Shopping', 'Green Area', 'Safe Locality'],
			cons: ['Crowded', 'Traffic Issues', 'Expensive'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 8800 },
				{ month: 'Feb 2024', averagePrice: 9100 },
				{ month: 'Mar 2024', averagePrice: 9300 },
				{ month: 'Apr 2024', averagePrice: 9500 },
			],
			neighboringLocalities: ['Viman Nagar', 'Baner', 'Camp'],
			description: 'Koregaon Park is Pune\'s upscale locality known for its restaurants, cafes, and vibrant social scene.',
			reviewCount: 267,
			averageRating: 4.2,
			searchCount: 9567,
			isPopular: true,
			developmentStatus: 'mature',
		},
	],
	Kolkata: [
		{
			name: 'Salt Lake',
			city: 'Kolkata',
			state: 'West Bengal',
			avgPricePerSqFt: 5500,
			growthPercentage: 6.2,
			sixMonthGrowth: 6.2,
			yearGrowth: 8.9,
			coordinates: { lat: 22.5726, lng: 88.4336 },
			geo: { type: 'Point', coordinates: [88.4336, 22.5726] },
			ratings: { safety: 7.9, connectivity: 8.0, lifestyle: 7.8, overall: 7.9 },
			amenities: {
				schools: 9,
				hospitals: 7,
				metro: true,
				markets: 8,
				parks: 4,
				malls: 4,
				banks: 8,
			},
			nearbyMetros: [
				{ name: 'Salt Lake Stadium', distance: 2.5 },
				{ name: 'Salt Lake South', distance: 3.2 },
			],
			pros: [
				'Planned City',
				'Safe & Clean',
				'Good Schools',
				'Metro Access',
				'Green Spaces',
			],
			cons: ['Far from City', 'Less Entertainment', 'Limited Nightlife'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 5000 },
				{ month: 'Feb 2024', averagePrice: 5200 },
				{ month: 'Mar 2024', averagePrice: 5400 },
				{ month: 'Apr 2024', averagePrice: 5500 },
			],
			neighboringLocalities: ['New Town', 'Rajarhat', 'Baguihati'],
			description:
				'Salt Lake is a well-planned residential area with excellent metro connectivity and family-oriented amenities.',
			reviewCount: 234,
			averageRating: 4.0,
			searchCount: 7654,
			isPopular: true,
			developmentStatus: 'mature',
		},
		{
			name: 'New Town',
			city: 'Kolkata',
			state: 'West Bengal',
			avgPricePerSqFt: 4200,
			growthPercentage: 8.7,
			sixMonthGrowth: 8.7,
			yearGrowth: 12.3,
			coordinates: { lat: 22.6097, lng: 88.4883 },
			geo: { type: 'Point', coordinates: [88.4883, 22.6097] },
			ratings: { safety: 7.6, connectivity: 7.9, lifestyle: 7.7, overall: 7.7 },
			amenities: {
				schools: 7,
				hospitals: 5,
				metro: true,
				markets: 6,
				parks: 5,
				malls: 2,
				banks: 6,
			},
			nearbyMetros: [{ name: 'New Town', distance: 1.5 }],
			pros: ['Emerging Area', 'Affordable', 'Good Growth', 'Planned Layout', 'Metro Access'],
			cons: ['Far from City', 'Still Developing', 'Less Entertainment'],
			priceTrend: [
				{ month: 'Jan 2024', averagePrice: 3800 },
				{ month: 'Feb 2024', averagePrice: 4000 },
				{ month: 'Mar 2024', averagePrice: 4100 },
				{ month: 'Apr 2024', averagePrice: 4200 },
			],
			neighboringLocalities: ['Salt Lake', 'Rajarhat', 'Baguihati'],
			description: 'New Town is a rapidly developing area with excellent growth potential and affordable property prices.',
			reviewCount: 145,
			averageRating: 3.8,
			searchCount: 5234,
			isPopular: true,
			developmentStatus: 'developing',
		},
	],
}

export const seedLocalities = async () => {
	try {
		const existingCount = await Locality.countDocuments()
		if (existingCount > 0) {
			console.log(`🔄 Clearing ${existingCount} old localities for fresh seed...`)
			await Locality.deleteMany({})
		}

		console.log('🌱 Seeding sample localities...')
		let insertedCount = 0

		for (const [city, localities] of Object.entries(LOCALITIES_BY_CITY)) {
			for (const locality of localities) {
				await Locality.create(locality)
				insertedCount++
			}
		}

		console.log(`✓ Successfully seeded ${insertedCount} sample localities`)
		return { inserted: insertedCount, skipped: false }
	} catch (error) {
		console.error('❌ Error seeding localities:', error.message)
		return { inserted: 0, error: error.message }
	}
}
